// Generated by tools/build.py from src/better-vest.user.js (@@BV-THEMES / @@BV-THEMEVARS markers).
// Do not edit here: change the source and rebuild.

export const THEMES = {
    astral: {
        label: 'Astral', tv: 'dark', base: '#070a13', card: '#0d1527',
        page: 'radial-gradient(circle at 50% 0%, #0e172a 0%, #070a13 55%, #05070d 100%)',
        chrome: 'rgba(7, 10, 19, 0.92)', chromeLine: 'rgba(56, 189, 248, 0.12)', surface: 'rgba(13, 21, 39, 0.88)',
        field: '#0b1220', fieldText: '#e2e8f0', fieldLine: '#334155',
        raised: 'rgba(15, 23, 42, 0.96)', inset: '#0b1220', btn: '#1e293b', line: '#334155',
        text: '#e2e8f0', muted: '#94a3b8', dim: '#64748b', accent: '#38bdf8', accentText: '#7dd3fc', sel: '#2563eb',
        up: '#34d399', down: '#f87171', upBtn: '#047857', downBtn: '#b91c1c', warn: '#f59e0b', big: '#fde68a',
        glow: 'rgba(56, 189, 248, 0.35)', shadow: 'rgba(0, 0, 0, 0.65)',
        chart: {
            bg: '#000000', grid: 'rgba(51, 65, 85, 0.28)', text: '#ffffff', line: '#ffffff', crosshair: '#ffffff', prevClose: true,
            up: '#b8b8b8', down: '#4a4a4a', borderUp: '#4a4a4a', borderDown: '#4a4a4a', wickUp: '#4a4a4a', wickDown: '#4a4a4a'
        }
    },
    dark: {
        label: 'Dark', tv: 'dark', tokens: true, base: '#0c0c0e', card: '#141417',
        page: '#0c0c0e',
        chrome: 'rgba(12, 12, 14, 0.96)', chromeLine: 'rgba(255, 255, 255, 0.06)', surface: 'rgba(20, 20, 23, 0.96)',
        field: '#0f0f12', fieldText: '#e4e4e7', fieldLine: '#2e2e33',
        raised: 'rgba(24, 24, 27, 0.97)', inset: '#0f0f12', btn: '#27272a', line: '#34343a',
        text: '#e4e4e7', muted: '#a1a1aa', dim: '#71717a', accent: '#60a5fa', accentText: '#93c5fd', sel: '#3b82f6',
        up: '#22c55e', down: '#ef4444', upBtn: '#15803d', downBtn: '#b91c1c', warn: '#f59e0b', big: '#fcd34d',
        glow: 'rgba(96, 165, 250, 0.28)', shadow: 'rgba(0, 0, 0, 0.6)',
        chart: {
            bg: '#0f0f11', grid: 'rgba(63, 63, 70, 0.32)', text: '#a1a1aa', up: '#00d68f', down: '#ff3b5c',
            borderUp: '#00d68f', borderDown: '#ff3b5c', wickUp: '#00d68f', wickDown: '#ff3b5c'
        }
    },
    oled: {
        label: 'OLED', tv: 'dark', tokens: true, base: '#000000', card: '#000000',
        page: '#000000',
        chrome: '#000000', chromeLine: 'rgba(255, 255, 255, 0.07)', surface: '#000000',
        field: '#000000', fieldText: '#f5f5f5', fieldLine: '#262626',
        raised: 'rgba(0, 0, 0, 0.97)', inset: '#000000', btn: '#111111', line: '#262626',
        text: '#f5f5f5', muted: '#a3a3a3', dim: '#737373', accent: '#ffffff', accentText: '#ffffff', sel: '#2a2a2a',
        up: '#00d68f', down: '#ff3b5c', upBtn: '#00995f', downBtn: '#c8102e', warn: '#ffb020', big: '#ffe08a',
        glow: 'rgba(255, 255, 255, 0.18)', shadow: 'rgba(0, 0, 0, 0.9)',
        chart: { bg: '#000000', grid: 'rgba(255, 255, 255, 0.04)', text: '#8a8a8a', up: '#00d68f', down: '#ff3b5c' }
    },
    light: {
        label: 'Light', tv: 'light', tokens: true, light: true, base: '#f3f5f9', card: '#ffffff',
        page: '#f3f5f9',
        chrome: 'rgba(255, 255, 255, 0.97)', chromeLine: '#e2e8f0', surface: '#ffffff',
        field: '#f8fafc', fieldText: '#0f172a', fieldLine: '#cbd5e1',
        raised: 'rgba(255, 255, 255, 0.98)', inset: '#f1f5f9', btn: '#e8edf4', line: '#d5dde8',
        text: '#0f172a', muted: '#475569', dim: '#64748b', accent: '#2563eb', accentText: '#1d4ed8', sel: '#2563eb',
        up: '#059669', down: '#dc2626', upBtn: '#059669', downBtn: '#dc2626', warn: '#d97706', big: '#b45309',
        glow: 'rgba(37, 99, 235, 0.25)', shadow: 'rgba(15, 23, 42, 0.18)',
        chart: { bg: '#ffffff', grid: 'rgba(15, 23, 42, 0.06)', text: '#475569', up: '#059669', down: '#dc2626' }
    },
    nebula: {
        label: 'Nebula', tv: 'dark', tokens: true, base: '#0a0612', card: '#160c28',
        page: 'radial-gradient(ellipse at 20% 0%, #2a1050 0%, #120822 45%, #07040f 100%)',
        chrome: 'rgba(14, 7, 26, 0.92)', chromeLine: 'rgba(192, 132, 252, 0.16)', surface: 'rgba(22, 12, 40, 0.88)',
        field: '#120a22', fieldText: '#f3e8ff', fieldLine: '#3b2a5c',
        raised: 'rgba(24, 13, 44, 0.96)', inset: '#120a22', btn: '#2a1a48', line: '#3d2b62',
        text: '#f3e8ff', muted: '#c4b5fd', dim: '#8b7bb8', accent: '#c084fc', accentText: '#e9d5ff', sel: '#9333ea',
        up: '#34d399', down: '#fb7185', upBtn: '#047857', downBtn: '#be123c', warn: '#f0abfc', big: '#fde68a',
        glow: 'rgba(192, 132, 252, 0.35)', shadow: 'rgba(0, 0, 0, 0.7)',
        chart: { bg: '#0b0616', grid: 'rgba(139, 92, 246, 0.12)', text: '#a78bfa', up: '#34d399', down: '#fb7185' }
    },
    ember: {
        label: 'Ember', tv: 'dark', tokens: true, base: '#0f0905', card: '#1c120b',
        page: 'radial-gradient(circle at 50% 0%, #2a1608 0%, #120b06 55%, #0a0604 100%)',
        chrome: 'rgba(18, 11, 6, 0.93)', chromeLine: 'rgba(245, 158, 11, 0.14)', surface: 'rgba(28, 18, 11, 0.9)',
        field: '#160e08', fieldText: '#fdecd2', fieldLine: '#4a3220',
        raised: 'rgba(30, 19, 11, 0.96)', inset: '#160e08', btn: '#3a2614', line: '#4a3220',
        text: '#fdecd2', muted: '#d6b48a', dim: '#9a7a58', accent: '#f59e0b', accentText: '#fbbf24', sel: '#c2410c',
        up: '#4ade80', down: '#f87171', upBtn: '#15803d', downBtn: '#b91c1c', warn: '#fb923c', big: '#fde68a',
        glow: 'rgba(245, 158, 11, 0.32)', shadow: 'rgba(0, 0, 0, 0.7)',
        chart: { bg: '#0f0905', grid: 'rgba(245, 158, 11, 0.07)', text: '#c9a77c', up: '#4ade80', down: '#f87171' }
    },
    terminal: {
        label: 'Terminal', tv: 'dark', tokens: true, base: '#020703', card: '#03100a',
        page: '#020703',
        chrome: 'rgba(2, 8, 4, 0.96)', chromeLine: 'rgba(34, 197, 94, 0.18)', surface: 'rgba(3, 12, 6, 0.94)',
        field: '#010502', fieldText: '#bbf7d0', fieldLine: '#14532d',
        raised: 'rgba(3, 12, 6, 0.97)', inset: '#010502', btn: '#062512', line: '#14532d',
        text: '#bbf7d0', muted: '#4ade80', dim: '#15803d', accent: '#22c55e', accentText: '#86efac', sel: '#15803d',
        up: '#22c55e', down: '#f87171', upBtn: '#15803d', downBtn: '#991b1b', warn: '#facc15', big: '#fef08a',
        glow: 'rgba(34, 197, 94, 0.32)', shadow: 'rgba(0, 0, 0, 0.8)',
        chart: { bg: '#010502', grid: 'rgba(34, 197, 94, 0.07)', text: '#4ade80', up: '#22c55e', down: '#03140a', borderDown: '#22c55e', wickDown: '#22c55e' }
    }
};

export function themeVarsCss(t) {
    return `
        :root {
            --ax-base: ${t.base}; --ax-page: ${t.page}; --ax-page-inner: ${t.pageInner || t.page};
            --ax-chrome: ${t.chrome}; --ax-chrome-line: ${t.chromeLine}; --ax-surface: ${t.surface};
            --ax-field: ${t.field}; --ax-field-text: ${t.fieldText}; --ax-field-line: ${t.fieldLine};
            --ax-raised: ${t.raised}; --ax-inset: ${t.inset}; --ax-btn: ${t.btn}; --ax-line: ${t.line};
            --ax-text: ${t.text}; --ax-muted: ${t.muted}; --ax-dim: ${t.dim};
            --ax-accent: ${t.accent}; --ax-accent-text: ${t.accentText}; --ax-sel: ${t.sel};
            --ax-up: ${t.up}; --ax-down: ${t.down}; --ax-up-btn: ${t.upBtn}; --ax-down-btn: ${t.downBtn};
            --ax-warn: ${t.warn}; --ax-big: ${t.big}; --ax-glow: ${t.glow}; --ax-shadow: ${t.shadow};
        }
    `;
}
