// Generated by tools/release.py keygen. The public half of the release signing key: an update is only
// installed when its files.json carries a signature this key accepts.
export const RELEASE_PUBLIC_KEY = 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEuSwvKFgVxX7pcGnefmtNW9gGH6qMED+1V7KbOe787OXiR4xa6jLu4M8vwpmQa6hLUf3XLboj8ijRkC/n/RtKZw==';
export const RELEASE_KEY_ID = 'dd66bcd666d48d5c';
